# Generated by Django 5.1.2 on 2024-11-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_about_contact_properties_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_title', models.CharField(max_length=255)),
                ('index_text', models.TextField()),
            ],
        ),
    ]
